name: start ubuntu

on:
  repository_dispatch:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '.config'


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
